In [1]:
import numpy as np

1-Crea un objeto numpy array con elementos del 10 al 50.


In [4]:
data = np.arange(10,51,1)
print(data)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


2-Cree una matriz bidimensional de 5*5 y mostrar por pantalla el tipo de elemento de la matriz.


In [6]:
data1 = np.zeros((5,5))
print(data1)
print(data.dtype.name)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
int64


3-Crear una matriz bidimensional. 
- Usar el índice para obtener el numero de la segunda fila y segunda columna.
- Usar el índice para obtener el numero de la segunda columna y tercera fila.
- Usar el índice para obtener el numero de la ultima columna y última fila.
- Usar el índice para obtener el numero de la primera columna y primera fila.

In [18]:
data3 = np.arange(25).reshape(5,5)
print(data3)
print('--------------')
print(data3[1,1])
print('--------------')
print(data3[2,1])
print('--------------')
print(data3[-1,-1])
print('--------------')
print(data3[0,0])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
--------------
6
--------------
11
--------------
24
--------------
0


4-Utiliza el índice booleano para generar los resultados del candidato C dados los siguientes datos.
-Nombres de los candidatos: candidatoA, candidatoB, candidatoC, candidatoD.
-Votos de los candidados en las mesas A1,B1 y C1 =
#### Candidato A =
- Mesa A1 = 10.1
- Mesa B1 = 5.4
- Mesa C1 = 21.2
#### Candidato B =
- Mesa A1 = 33.1
- Mesa B1 = 40.2
- Mesa C1 = 33.7
#### Candidato C =
- Mesa A1 = 33.1
- Mesa B1 = 40.2
- Mesa C1 = 33.7
#### Candidato D =
- Mesa A1 = 50.1
- Mesa B1 = 40.5
- Mesa C1 = 30.1


In [24]:
candidatos_nombre = np.array(['CandidatoA','CandidatoB','CandidatoC','CandidatoD'])
votos_candidatos_mesas_1A1B1C = np.array([[10.1,5.4,21.1],[33.1,40.2,33.7],[9.1,7.8,4.1],[50.1,40.5,30.1]])
print(candidatos_nombre)
print(votos_candidatos_mesas_1A1B1C)
print("Los votos del Candidato C son ",votos_candidatos_mesas_1A1B1C[candidatos_nombre=='CandidatoC'])



['CandidatoA' 'CandidatoB' 'CandidatoC' 'CandidatoD']
[[10.1  5.4 21.1]
 [33.1 40.2 33.7]
 [ 9.1  7.8  4.1]
 [50.1 40.5 30.1]]
Los votos del Candidato C son  [[9.1 7.8 4.1]]


5-Crear una matriz de 4x4 con valores que van de 0 a 15.

In [28]:
matriz5 = np.arange(16).reshape(4, 4)
print(matriz5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


6- Crear una matriz de 10x10 con el valor 1 en todos sus bordes y 0 en su interior.

In [103]:
bordes = np.ones((5,5))
bordes[1:-1,1:-1] = 0
print(bordes)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


7-Crea una matriz de 5x5 con los valores 1,2,3,4 justo debajo de la diagonal.

In [33]:
diagonal = np.diag(1+np.arange(4),k=-1)
print(diagonal)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


8-Imprima el valor mínimo y máximo representable para cada tipo escalar en numpy.

In [34]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


9-Dado un array de dos dimensiones, mostrar si este tiene un valor null.

In [101]:
array9 = np.random.randint(0,3,(3,10))
array10 = np.array([np.NaN,1,2,np.NaN,3])
print(array9)
print(array10)
if(np.isnan(array9).any()):
    print("La matriz contiene valores NaN")
else:
    print("La matriz no contiene valores NaN")
print("----------------------")
if(np.isnan(array10).any()):
    print("La matriz contiene valores NaN")
else:
    print("La matriz no contiene valores NaN")
    

[[1 2 2 0 1 2 2 0 2 2]
 [1 1 1 0 1 2 1 0 0 1]
 [2 2 2 2 0 0 0 1 2 1]]
[nan  1.  2. nan  3.]
La matriz no contiene valores NaN
----------------------
La matriz contiene valores NaN


10-Encontrar el valor más cercano de un valor dado en una matriz.

In [85]:
matriz = np.random.uniform(0,1,10)
valor_dado = 5
resultado = matriz.flat[np.abs(matriz - valor_dado).argmin()]
print(resultado)

0.956193871974871


11-Considerando una matriz de dimensión (5,5,3),multiplicarla por una matriz con dimensiones(5,5).

In [105]:
A = np.ones((5,5,3))
print(A)
print("----------------------")
B = 3*np.ones((5,5))
print(B)
print("----------------------")
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
----------------------
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
----------------------
[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


12-Tomando el vector [1, 2, 3, 4, 5], construir un nuevo vector con 3 ceros consecutivos intercalados entre cada valor.

In [61]:
array = np.array([1,2,3,4,5])
ceros_consecutivos = 3
nuevo_array = np.zeros(len(array) + (len(array)-1)*(ceros_consecutivos))
nuevo_array[::ceros_consecutivos+1] = array
print(nuevo_array)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


13-Encontrar el valor más frecuente en un array.

In [78]:
array = np.random.randint(0,10,50)
print(array)
print("El valor más frecuente es ",np.bincount(array).argmax())

[5 8 5 5 5 5 6 9 1 9 0 5 0 0 7 9 2 1 7 7 1 2 8 5 5 7 1 8 7 7 5 2 6 2 9 2 8
 7 0 6 7 0 0 6 5 4 9 6 8 4]
El valor más frecuente es  5


14-Obtener los n valores más grandes de una matriz.

In [76]:
matriz = np.arange(100)
np.random.shuffle(matriz)
n = 4
print (matriz[np.argpartition(-matriz,n)[:n]])

[99 97 98 96]


15-Tomando una matriz de 10x3, extraer las filas con valores desiguales y mostrarlas por pantalla.

In [71]:
array = np.random.randint(0,5,(10,3))
print(array)
print('---------------')
E = np.all(array[:,1:] == array[:,:-1], axis=1)
U = array[~E]
print(U)

[[0 4 3]
 [2 0 1]
 [0 2 4]
 [1 4 4]
 [2 2 0]
 [1 1 1]
 [0 4 2]
 [0 3 4]
 [2 0 1]
 [0 3 0]]
---------------
[[0 4 3]
 [2 0 1]
 [0 2 4]
 [1 4 4]
 [2 2 0]
 [0 4 2]
 [0 3 4]
 [2 0 1]
 [0 3 0]]
